/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaymentSuccessRouteImport } from './routes/payment/success'
import { Route as PaymentReturnRouteImport } from './routes/payment/return'
import { Route as PaymentFailedRouteImport } from './routes/payment/failed'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as appProfileRouteImport } from './routes/(app)/profile'
import { Route as appHangarRouteImport } from './routes/(app)/hangar'
import { Route as appFlightDeckRouteImport } from './routes/(app)/flight-deck'
import { Route as appCoPilotRouteImport } from './routes/(app)/co-pilot'
import { Route as appAdminRouteImport } from './routes/(app)/admin'
import { Route as ApiPaymongoWebhookRouteImport } from './routes/api/paymongo/webhook'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentReturnRoute = PaymentReturnRouteImport.update({
  id: '/payment/return',
  path: '/payment/return',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailedRoute = PaymentFailedRouteImport.update({
  id: '/payment/failed',
  path: '/payment/failed',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const appProfileRoute = appProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => appRouteRoute,
} as any)
const appHangarRoute = appHangarRouteImport.update({
  id: '/hangar',
  path: '/hangar',
  getParentRoute: () => appRouteRoute,
} as any)
const appFlightDeckRoute = appFlightDeckRouteImport.update({
  id: '/flight-deck',
  path: '/flight-deck',
  getParentRoute: () => appRouteRoute,
} as any)
const appCoPilotRoute = appCoPilotRouteImport.update({
  id: '/co-pilot',
  path: '/co-pilot',
  getParentRoute: () => appRouteRoute,
} as any)
const appAdminRoute = appAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => appRouteRoute,
} as any)
const ApiPaymongoWebhookRoute = ApiPaymongoWebhookRouteImport.update({
  id: '/api/paymongo/webhook',
  path: '/api/paymongo/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/admin': typeof appAdminRoute
  '/co-pilot': typeof appCoPilotRoute
  '/flight-deck': typeof appFlightDeckRoute
  '/hangar': typeof appHangarRoute
  '/profile': typeof appProfileRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/return': typeof PaymentReturnRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/paymongo/webhook': typeof ApiPaymongoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/admin': typeof appAdminRoute
  '/co-pilot': typeof appCoPilotRoute
  '/flight-deck': typeof appFlightDeckRoute
  '/hangar': typeof appHangarRoute
  '/profile': typeof appProfileRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/return': typeof PaymentReturnRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/paymongo/webhook': typeof ApiPaymongoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/(app)/admin': typeof appAdminRoute
  '/(app)/co-pilot': typeof appCoPilotRoute
  '/(app)/flight-deck': typeof appFlightDeckRoute
  '/(app)/hangar': typeof appHangarRoute
  '/(app)/profile': typeof appProfileRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/signup': typeof authSignupRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/return': typeof PaymentReturnRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/paymongo/webhook': typeof ApiPaymongoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/admin'
    | '/co-pilot'
    | '/flight-deck'
    | '/hangar'
    | '/profile'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/payment/failed'
    | '/payment/return'
    | '/payment/success'
    | '/api/auth/$'
    | '/api/paymongo/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/admin'
    | '/co-pilot'
    | '/flight-deck'
    | '/hangar'
    | '/profile'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/payment/failed'
    | '/payment/return'
    | '/payment/success'
    | '/api/auth/$'
    | '/api/paymongo/webhook'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/checkout'
    | '/(app)/admin'
    | '/(app)/co-pilot'
    | '/(app)/flight-deck'
    | '/(app)/hangar'
    | '/(app)/profile'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/reset-password'
    | '/(auth)/signup'
    | '/payment/failed'
    | '/payment/return'
    | '/payment/success'
    | '/api/auth/$'
    | '/api/paymongo/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignupRoute: typeof authSignupRoute
  PaymentFailedRoute: typeof PaymentFailedRoute
  PaymentReturnRoute: typeof PaymentReturnRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPaymongoWebhookRoute: typeof ApiPaymongoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/return': {
      id: '/payment/return'
      path: '/payment/return'
      fullPath: '/payment/return'
      preLoaderRoute: typeof PaymentReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/failed': {
      id: '/payment/failed'
      path: '/payment/failed'
      fullPath: '/payment/failed'
      preLoaderRoute: typeof PaymentFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/profile': {
      id: '/(app)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appProfileRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/hangar': {
      id: '/(app)/hangar'
      path: '/hangar'
      fullPath: '/hangar'
      preLoaderRoute: typeof appHangarRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/flight-deck': {
      id: '/(app)/flight-deck'
      path: '/flight-deck'
      fullPath: '/flight-deck'
      preLoaderRoute: typeof appFlightDeckRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/co-pilot': {
      id: '/(app)/co-pilot'
      path: '/co-pilot'
      fullPath: '/co-pilot'
      preLoaderRoute: typeof appCoPilotRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/admin': {
      id: '/(app)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof appAdminRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/api/paymongo/webhook': {
      id: '/api/paymongo/webhook'
      path: '/api/paymongo/webhook'
      fullPath: '/api/paymongo/webhook'
      preLoaderRoute: typeof ApiPaymongoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface appRouteRouteChildren {
  appAdminRoute: typeof appAdminRoute
  appCoPilotRoute: typeof appCoPilotRoute
  appFlightDeckRoute: typeof appFlightDeckRoute
  appHangarRoute: typeof appHangarRoute
  appProfileRoute: typeof appProfileRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAdminRoute: appAdminRoute,
  appCoPilotRoute: appCoPilotRoute,
  appFlightDeckRoute: appFlightDeckRoute,
  appHangarRoute: appHangarRoute,
  appProfileRoute: appProfileRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignupRoute: authSignupRoute,
  PaymentFailedRoute: PaymentFailedRoute,
  PaymentReturnRoute: PaymentReturnRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPaymongoWebhookRoute: ApiPaymongoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
