/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as marketingRouteRouteImport } from './routes/(marketing)/route'
import { Route as adminRouteRouteImport } from './routes/(admin)/route'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as marketingIndexRouteImport } from './routes/(marketing)/index'
import { Route as ShareShareTokenRouteImport } from './routes/share.$shareToken'
import { Route as PaymentSuccessRouteImport } from './routes/payment/success'
import { Route as PaymentReturnRouteImport } from './routes/payment/return'
import { Route as PaymentFailedRouteImport } from './routes/payment/failed'
import { Route as PaymentCheckoutRouteImport } from './routes/payment/checkout'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppHangarRouteImport } from './routes/app/hangar'
import { Route as AppCoPilotRouteImport } from './routes/app/co-pilot'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as adminAdminRouteImport } from './routes/(admin)/admin'
import { Route as ApiPaymongoWebhookRouteImport } from './routes/api/paymongo/webhook'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingRouteRoute = marketingRouteRouteImport.update({
  id: '/(marketing)',
  getParentRoute: () => rootRouteImport,
} as any)
const adminRouteRoute = adminRouteRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const marketingIndexRoute = marketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => marketingRouteRoute,
} as any)
const ShareShareTokenRoute = ShareShareTokenRouteImport.update({
  id: '/share/$shareToken',
  path: '/share/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentReturnRoute = PaymentReturnRouteImport.update({
  id: '/payment/return',
  path: '/payment/return',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailedRoute = PaymentFailedRouteImport.update({
  id: '/payment/failed',
  path: '/payment/failed',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCheckoutRoute = PaymentCheckoutRouteImport.update({
  id: '/payment/checkout',
  path: '/payment/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHangarRoute = AppHangarRouteImport.update({
  id: '/hangar',
  path: '/hangar',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCoPilotRoute = AppCoPilotRouteImport.update({
  id: '/co-pilot',
  path: '/co-pilot',
  getParentRoute: () => AppRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const adminAdminRoute = adminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => adminRouteRoute,
} as any)
const ApiPaymongoWebhookRoute = ApiPaymongoWebhookRouteImport.update({
  id: '/api/paymongo/webhook',
  path: '/api/paymongo/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteRouteWithChildren
  '/admin': typeof adminAdminRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/app/co-pilot': typeof AppCoPilotRoute
  '/app/hangar': typeof AppHangarRoute
  '/app/profile': typeof AppProfileRoute
  '/payment/checkout': typeof PaymentCheckoutRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/return': typeof PaymentReturnRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
  '/': typeof marketingIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/paymongo/webhook': typeof ApiPaymongoWebhookRoute
}
export interface FileRoutesByTo {
  '/admin': typeof adminAdminRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/app/co-pilot': typeof AppCoPilotRoute
  '/app/hangar': typeof AppHangarRoute
  '/app/profile': typeof AppProfileRoute
  '/payment/checkout': typeof PaymentCheckoutRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/return': typeof PaymentReturnRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
  '/': typeof marketingIndexRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/paymongo/webhook': typeof ApiPaymongoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(admin)': typeof adminRouteRouteWithChildren
  '/(marketing)': typeof marketingRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/(admin)/admin': typeof adminAdminRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/signup': typeof authSignupRoute
  '/app/co-pilot': typeof AppCoPilotRoute
  '/app/hangar': typeof AppHangarRoute
  '/app/profile': typeof AppProfileRoute
  '/payment/checkout': typeof PaymentCheckoutRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/return': typeof PaymentReturnRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
  '/(marketing)/': typeof marketingIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/paymongo/webhook': typeof ApiPaymongoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app/co-pilot'
    | '/app/hangar'
    | '/app/profile'
    | '/payment/checkout'
    | '/payment/failed'
    | '/payment/return'
    | '/payment/success'
    | '/share/$shareToken'
    | '/'
    | '/app/'
    | '/api/auth/$'
    | '/api/paymongo/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app/co-pilot'
    | '/app/hangar'
    | '/app/profile'
    | '/payment/checkout'
    | '/payment/failed'
    | '/payment/return'
    | '/payment/success'
    | '/share/$shareToken'
    | '/'
    | '/app'
    | '/api/auth/$'
    | '/api/paymongo/webhook'
  id:
    | '__root__'
    | '/(admin)'
    | '/(marketing)'
    | '/app'
    | '/(admin)/admin'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/reset-password'
    | '/(auth)/signup'
    | '/app/co-pilot'
    | '/app/hangar'
    | '/app/profile'
    | '/payment/checkout'
    | '/payment/failed'
    | '/payment/return'
    | '/payment/success'
    | '/share/$shareToken'
    | '/(marketing)/'
    | '/app/'
    | '/api/auth/$'
    | '/api/paymongo/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  adminRouteRoute: typeof adminRouteRouteWithChildren
  marketingRouteRoute: typeof marketingRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignupRoute: typeof authSignupRoute
  PaymentCheckoutRoute: typeof PaymentCheckoutRoute
  PaymentFailedRoute: typeof PaymentFailedRoute
  PaymentReturnRoute: typeof PaymentReturnRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ShareShareTokenRoute: typeof ShareShareTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPaymongoWebhookRoute: typeof ApiPaymongoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)': {
      id: '/(marketing)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof marketingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)': {
      id: '/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(marketing)/': {
      id: '/(marketing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof marketingIndexRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/share/$shareToken': {
      id: '/share/$shareToken'
      path: '/share/$shareToken'
      fullPath: '/share/$shareToken'
      preLoaderRoute: typeof ShareShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/return': {
      id: '/payment/return'
      path: '/payment/return'
      fullPath: '/payment/return'
      preLoaderRoute: typeof PaymentReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/failed': {
      id: '/payment/failed'
      path: '/payment/failed'
      fullPath: '/payment/failed'
      preLoaderRoute: typeof PaymentFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/checkout': {
      id: '/payment/checkout'
      path: '/payment/checkout'
      fullPath: '/payment/checkout'
      preLoaderRoute: typeof PaymentCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/hangar': {
      id: '/app/hangar'
      path: '/hangar'
      fullPath: '/app/hangar'
      preLoaderRoute: typeof AppHangarRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/co-pilot': {
      id: '/app/co-pilot'
      path: '/co-pilot'
      fullPath: '/app/co-pilot'
      preLoaderRoute: typeof AppCoPilotRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/admin': {
      id: '/(admin)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof adminAdminRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/api/paymongo/webhook': {
      id: '/api/paymongo/webhook'
      path: '/api/paymongo/webhook'
      fullPath: '/api/paymongo/webhook'
      preLoaderRoute: typeof ApiPaymongoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface adminRouteRouteChildren {
  adminAdminRoute: typeof adminAdminRoute
}

const adminRouteRouteChildren: adminRouteRouteChildren = {
  adminAdminRoute: adminAdminRoute,
}

const adminRouteRouteWithChildren = adminRouteRoute._addFileChildren(
  adminRouteRouteChildren,
)

interface marketingRouteRouteChildren {
  marketingIndexRoute: typeof marketingIndexRoute
}

const marketingRouteRouteChildren: marketingRouteRouteChildren = {
  marketingIndexRoute: marketingIndexRoute,
}

const marketingRouteRouteWithChildren = marketingRouteRoute._addFileChildren(
  marketingRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppCoPilotRoute: typeof AppCoPilotRoute
  AppHangarRoute: typeof AppHangarRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCoPilotRoute: AppCoPilotRoute,
  AppHangarRoute: AppHangarRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  adminRouteRoute: adminRouteRouteWithChildren,
  marketingRouteRoute: marketingRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignupRoute: authSignupRoute,
  PaymentCheckoutRoute: PaymentCheckoutRoute,
  PaymentFailedRoute: PaymentFailedRoute,
  PaymentReturnRoute: PaymentReturnRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ShareShareTokenRoute: ShareShareTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPaymongoWebhookRoute: ApiPaymongoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
